name: CI
on: [push, pull_request]
env:
  HUSKY: 0
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install yarn
        run: npm i -g yarn
      - name: Run yarn install
        run: yarn install --check-cache
      - name: Run build
        run: yarn build
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build and run API Extractor
        run: yarn build
      - uses: EndBug/add-and-commit@v7
        with:
          branch: ${{ github.head_ref || github.ref }}
          message: "ci: API Extractor"
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Tests
        run: yarn test