name: CI
on: [push, pull_request]
env:
  HUSKY: 0
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install yarn
        run: npm i -g yarn
      - name: Check user permission
        id: check
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run yarn
        if: steps.check.outputs.has-permission
        run: yarn
      - name: Run yarn with cache check
        if: "! steps.check.outputs.has-permission"
        run: yarn --check-cache
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run API Extractor
        run: yarn build
      - uses: EndBug/add-and-commit@v7
        with:
          branch: ${{ github.head_ref || github.ref }}
          message: "ci: API Extractor"
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: yarn test