name: Carbon docs
on: [push]
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install yarn
        run: npm i -g yarn
      - name: Run yarn
        run: yarn
      - name: Make docs
        run: yarn typedoc packages --json docs.json
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'docs: make docs'