name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: Install modules
        run: |
          npm i
          npx lerna bootstrap
      - name: Run tests
        run: npx lerna run test
      - name: Code style checks
        run: npm run lint
