name: Carbon workflows
on: 
  push:
    paths-ignore:
      - "docs.json"
  pull_request:
    paths-ignore:
      - "docs.json"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install yarn
        run: npm i -g yarn
      - name: Run yarn
        run: yarn install --check-cache
      - name: Run ESLint
        run: yarn lint
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install yarn
        run: npm i -g yarn
      - name: Run yarn
        run: yarn install --check-cache
      - name: Run tests
        run: yarn test